"""Write SKILL.md files for captured skills and render `_index.md` +
`_categories.md` into `~/.claude/skills/`.

§6.1 + §6.3: no runtime ranking, no top-k truncation. Three render groups:
preset-main (manual_only=0), manual-only, uncategorized. Manual skills are
NEVER rewritten here — we only touch their disk copy if the user `/skill
review accept`s a proposed change in v0.2+.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from .models import SkillRecord
from .store import Store, atomic_write_text


GENERATED_BY_MARKER = "skillsynapse"


def _render_frontmatter(skill: SkillRecord) -> str:
    fm: dict = {
        "name": skill.name,
        "description": skill.description or "",
        "version": skill.version,
        # Marks this file as SkillSynapse-owned. bootstrap.py uses this to
        # avoid re-importing our own output as a user-authored manual skill
        # after the DB is rebuilt or a prune removes the matching row.
        "generated_by": GENERATED_BY_MARKER,
    }
    if skill.category:
        fm["category"] = skill.category
    if skill.trigger:
        fm["trigger"] = skill.trigger
    if skill.tags:
        fm["tags"] = skill.tags
    if skill.tool_dependencies:
        fm["tool_dependencies"] = skill.tool_dependencies
    if skill.critical_tools:
        fm["critical_tools"] = skill.critical_tools
    return yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()


def write_skill_md(skill: SkillRecord, skills_root: Path) -> Path:
    """Atomically (re)write a captured skill's SKILL.md. Never writes manual skills."""
    if skill.manual_protected or skill.origin == "manual":
        raise ValueError(
            f"refusing to write manual-protected skill '{skill.name}' to disk "
            f"(origin={skill.origin}, manual_protected={skill.manual_protected})"
        )
    skill_dir = skills_root / skill.name
    target = skill_dir / "SKILL.md"
    fm = _render_frontmatter(skill)
    body = skill.content or ""
    doc = f"---\n{fm}\n---\n\n{body.rstrip()}\n"
    atomic_write_text(target, doc)
    return target


# ── Hierarchy rendering ──────────────────────────────────────────

def _group_skills(active: list[SkillRecord], categories: list[dict]) -> tuple[
    list[tuple[dict, list[SkillRecord]]],       # main preset (manual_only=0) with >=1 skill
    list[tuple[dict, list[SkillRecord]]],       # manual_only with >=1 skill
    list[SkillRecord],                           # uncategorized
]:
    by_cat: dict[str, list[SkillRecord]] = {}
    uncategorized: list[SkillRecord] = []
    for s in active:
        if s.category:
            by_cat.setdefault(s.category, []).append(s)
        else:
            uncategorized.append(s)
    main: list[tuple[dict, list[SkillRecord]]] = []
    manual: list[tuple[dict, list[SkillRecord]]] = []
    for cat in categories:
        skills = by_cat.get(cat["slug"], [])
        if not skills:
            continue
        (manual if cat["manual_only"] else main).append((cat, skills))
    main.sort(key=lambda item: item[0]["slug"])
    manual.sort(key=lambda item: item[0]["slug"])
    uncategorized.sort(key=lambda s: s.name)
    for _, skills in main + manual:
        skills.sort(key=lambda s: s.name)
    return main, manual, uncategorized


def render_index_md(store: Store, paths_index_md: Path) -> None:
    active = store.list_active_skills()
    cats = store.list_categories()
    main, manual_only, uncategorized = _group_skills(active, cats)

    lines = [
        "<!-- AUTO-GENERATED by SkillSynapse; do not edit by hand -->",
        "<available_skills>",
    ]
    if main:
        lines.append("  # —— Main preset categories (extractor-owned) ——")
        for cat, skills in main:
            lines.append(f"  {cat['slug']}: {cat['description']}")
            for s in skills:
                desc = (s.description or "").splitlines()[0][:220] or "(no description)"
                lines.append(f"    - {s.name}: {desc}")
    if manual_only:
        lines.append("")
        lines.append("  # —— Manual-only categories (user-defined) ——")
        for cat, skills in manual_only:
            lines.append(f"  {cat['slug']}: {cat['description']}")
            for s in skills:
                desc = (s.description or "").splitlines()[0][:220] or "(no description)"
                lines.append(f"    - {s.name}: {desc}")
    if uncategorized:
        lines.append("")
        lines.append("  # —— Uncategorized (no `category` in frontmatter) ——")
        lines.append("  uncategorized: manual skills without a declared category")
        for s in uncategorized:
            desc = (s.description or "").splitlines()[0][:220] or "(no description)"
            lines.append(f"    - {s.name}: {desc}")
    if not (main or manual_only or uncategorized):
        lines.append("  (no active skills yet)")
    lines.append("</available_skills>")
    atomic_write_text(paths_index_md, "\n".join(lines) + "\n")


def render_categories_md(store: Store, path: Path) -> None:
    cats = store.list_categories()
    main = [c for c in cats if not c["manual_only"]]
    manual = [c for c in cats if c["manual_only"]]

    lines = [
        "# Categories (rendered by SkillSynapse; do not edit by hand)",
        "",
        "## Main (extractor-owned, capped at 15)",
        "",
    ]
    for c in main:
        lines.append(f"- {c['slug']}: {c['description']}")
    lines.append("")
    lines.append("## Manual-only (user-defined)")
    lines.append("")
    if manual:
        for c in manual:
            lines.append(f"- {c['slug']}: {c['description']}")
    else:
        lines.append("_(none)_")
    lines.append("")
    lines.append("## Uncategorized")
    lines.append("")
    lines.append(
        "Manual skills whose frontmatter doesn't declare a `category` are "
        "grouped here in `_index.md`."
    )
    atomic_write_text(path, "\n".join(lines) + "\n")


def sync_captured_skill_files(store: Store, skills_root: Path) -> int:
    """Ensure every active captured skill has a SKILL.md on disk. Returns the
    count of files written/updated."""
    written = 0
    for skill in store.list_active_skills():
        if skill.manual_protected or skill.origin == "manual":
            continue
        write_skill_md(skill, skills_root)
        written += 1
    return written
